# Generated by Django 2.1.4 on 2018-12-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiemstamp',
            new_name='timestamp',
        ),
    ]
